@extends('layouts.app')
@section('title')
    Dashboard
@endsection
@section('content')
@endsection
@section('sidenavbar')
    @include('layouts.sidenavbar')
@endsection
@section('topnavbar')
    @include('layouts.topnavbar')
@endsection
